name: Update Good First Issues

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch: 

jobs:
  update-good-first-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Generate Good First Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run main.go --issues

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/*
          git commit -m "Update Issues"
          git push
