name: Generate and Publish GitHub Report

on: workflow_dispatch

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23' # Specify your Go version

    - name: Install Dependencies
      run: go mod tidy

    # Run the server and generate the report
    - name: Generate HTML Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p docs
        go run main.go

    # Publish to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        publish_branch: gh-pages
